tests/util: Fix linker error caused by is_power_of_two()
On Fedora 42 with gcc v15.1.1 and ld v2.44 the tests fail to compile
with error:

FAILED: tests/modetest/modetest
cc  -o tests/modetest/modetest tests/modetest/modetest.p/buffers.c.o \
       tests/modetest/modetest.p/cursor.c.o \
       tests/modetest/modetest.p/modetest.c.o \
       -Wl,--as-needed -Wl,--no-undefined '-Wl,-rpath,$ORIGIN/../..' \
       -Wl,--start-group libdrm.so.2.125.0 tests/util/libutil.a \
       -lm -pthread /usr/lib64/libcairo.so -Wl,--end-group
/usr/bin/ld: tests/util/libutil.a.p/pattern.c.o: in function `check_yuv':
./libdrm/tests/util/pattern.c:1989:(.text+0x9ea7):
             undefined reference to `is_power_of_two'
/usr/bin/ld: ./libdrm/tests/util/pattern.c:1990:(.text+0x9ec0):
             undefined reference to `is_power_of_two'
/usr/bin/ld: ./libdrm/tests/util/pattern.c:1991:(.text+0x9ee9):
             undefined reference to `is_power_of_two'
collect2: error: ld returned 1 exit status

Fixes: 40aeab6fd5b8 ("modetest: util: pattern: add new patterns")
Signed-off-by: José Expósito <jose.exposito89@gmail.com>